name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
          cache-dependency-path: 'poetry.lock'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Run migrations
        run: poetry run python manage.py migrate

      - name: Run tests
        run: poetry run python manage.py test
