name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --with lint --no-interaction --no-root

      - name: Run linters
        run: |
          poetry run black --check .
          poetry run isort --check .
          poetry run flake8 .

      - name: Run migrate
        run: poetry run python manage.py migrate

      - name: Run tests
        run: poetry run python manage.py test
